In [7]:
# load the file merged_results_enriched_and_modified

import pandas as pd

df = pd.read_csv("merged_results_enriched_and_modified.csv")

df[["PathBoostAccuracy_times 100", 'PathBoostAccuracy_times_100']].max(axis=1)
df['PB_accuracy'] = df['PB_accuracy'] * 100
df['PathBoostAccuracy_times 100'] = df[
    ["PathBoostAccuracy_times 100", 'PathBoostAccuracy_times_100', 'PB_accuracy']].max(axis=1)
print(len(df))
df = df.loc[df['PathBoostAccuracy_times 100'] >= 1]

# remove all the negative values
def remove_neg_value(x):
    try:
        if x < 0:
            return None
        else:
            return x
    except:
        return x

df =  df.map(remove_neg_value)



df

69

,Dataset,Graphs,AvgNodes,AvgEdges,NodeFeatures,EdgeFeatures,TotalFeatures,ClassPercentages,CatAttrClasses,PathBoostAccuracy_times 100,...,PB_f1_macro_std10,PB_f1_macro_std100,PB_f1_std10,PB_f1_std100,PB_recall,PB_recall_std10,PB_recall_std100,ClassPercentages.1,fist_class_percentage,n_graphs_firs_class
0,AIDS,2000.0,15.69,16.20,5.0,1.0,6.0,"0: 20.00%, 1: 80.00%",38.0,99.330000,...,0.001240,0.009281,0.000530,0.003651,0.998114,0.001189,0.003747,"0: 20.00%, 1: 80.00%",20.000,400
1,BZR,405.0,35.75,38.36,4.0,0.0,4.0,"-1: 78.77%, 1: 21.23%",10.0,86.764634,...,0.018082,0.098682,0.033344,0.175372,0.405789,0.030250,0.173194,"-1: 78.77%, 1: 21.23%",78.770,86
5,DHFR,756.0,42.43,44.54,4.0,0.0,4.0,"-1: 39.02%, 1: 60.98%",9.0,78.190000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-1: 39.02%, 1: 60.98%",39.020,461
8,MCF-7,27770.0,26.40,28.53,1.0,1.0,2.0,"0: 91.74%, 1: 8.26%",46.0,92.236586,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 91.74%, 1: 8.26%",91.740,2294
9,MCF-7H,27770.0,47.31,49.44,1.0,1.0,2.0,"0: 91.74%, 1: 8.26%",47.0,92.240187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 91.74%, 1: 8.26%",91.740,2294
11,MUTAG,188.0,17.93,19.79,1.0,1.0,2.0,"-1: 33.51%, 1: 66.49%",7.0,89.111111,...,0.021065,0.094836,0.014155,0.072463,0.910170,0.017287,0.091759,"-1: 33.51%, 1: 66.49%",33.510,125
12,NCI-H23,40353.0,26.07,28.10,1.0,1.0,2.0,"0: 94.90%, 1: 5.10%",65.0,95.179044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 94.90%, 1: 5.10%",94.900,2058
17,PROTEINS_full,1113.0,39.06,72.82,30.0,0.0,30.0,"1: 59.57%, 2: 40.43%",3.0,78.995656,...,0.010371,0.053907,0.016827,0.081812,0.566054,0.021385,0.100669,"1: 59.57%, 2: 40.43%",59.457,451
18,PTC_FM,349.0,14.11,14.48,1.0,1.0,2.0,"-1: 59.03%, 1: 40.97%",18.0,61.800840,...,0.019132,0.089848,0.026307,0.133401,0.320889,0.025251,0.140366,"-1: 59.03%, 1: 40.97%",59.030,143
19,PTC_FR,351.0,14.56,15.00,1.0,1.0,2.0,"-1: 65.53%, 1: 34.47%",0.0,63.842857,...,0.027652,0.088399,0.046591,0.151760,0.235669,0.049152,0.159046,"-1: 65.53%, 1: 34.47%",NaN,351
20,PTC_MM,336.0,13.97,14.32,1.0,1.0,2.0,"-1: 61.61%, 1: 38.39%",0.0,61.623886,...,0.018083,0.107477,0.031960,0.167600,0.341041,0.038804,0.184737,"-1: 61.61%, 1: 38.39%",NaN,336
21,PTC_MR,344.0,14.29,14.69,1.0,1.0,2.0,"-1: 55.81%, 1: 44.19%",0.0,54.073109,...,0.020729,0.094244,0.044196,0.165221,0.364621,0.058511,0.205103,"-1: 55.81%, 1: 44.19%",NaN,344
23,SF-295,40271.0,26.06,28.09,1.0,1.0,2.0,"0: 94.97%, 1: 5.03%",65.0,95.265329,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 94.97%, 1: 5.03%",94.970,2026
25,SW-620,40532.0,26.06,28.09,1.0,1.0,2.0,"0: 94.05%, 1: 5.95%",65.0,94.391595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 94.05%, 1: 5.95%",94.050,2412
27,SYNTHETIC,300.0,100.00,196.00,2.0,0.0,2.0,"0: 50.00%, 1: 50.00%",8.0,62.266667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 50.00%, 1: 50.00%",50.000,150
29,Tox21_AR-LBD_evaluation,580.0,17.09,17.42,1.0,1.0,2.0,"0: 98.62%, 1: 1.38%",23.0,98.603448,...,0.059111,0.241157,0.000000,0.000000,0.000000,0.000000,0.000000,"0: 98.62%, 1: 1.38%",98.620,8
30,Tox21_AR-LBD_testing,253.0,21.85,22.73,1.0,1.0,2.0,"0: 98.42%, 1: 1.58%",15.0,98.415385,...,0.042714,0.255453,0.000000,0.000000,0.000000,0.000000,0.000000,"0: 98.42%, 1: 1.58%",98.420,4
31,Tox21_AR-LBD_training,8599.0,17.77,18.16,1.0,1.0,2.0,"0: 96.48%, 1: 3.52%",49.0,98.099770,...,0.002782,0.041439,0.005453,0.081129,0.572748,0.008434,0.096291,"0: 96.48%, 1: 3.52%",96.480,303
32,Tox21_ARE_evaluation,552.0,17.01,17.33,1.0,1.0,2.0,"0: 83.51%, 1: 16.49%",25.0,83.370455,...,0.019897,0.077447,0.038817,0.140956,0.101757,0.032808,0.113267,"0: 83.51%, 1: 16.49%",83.510,91
33,Tox21_ARE_testing,234.0,21.99,22.91,1.0,1.0,2.0,"0: 79.49%, 1: 20.51%",15.0,79.398551,...,0.018859,0.117131,0.031082,0.218373,0.210258,0.034192,0.216353,"0: 79.49%, 1: 20.51%",79.490,48
34,Tox21_ARE_training,7167.0,16.28,16.52,1.0,1.0,2.0,"0: 84.68%, 1: 15.32%",46.0,84.785949,...,0.007131,0.019160,0.013871,0.036778,0.047946,0.007929,0.021283,"0: 84.68%, 1: 15.32%",84.680,1098
35,Tox21_AR_evaluation,585.0,17.99,18.45,1.0,1.0,2.0,"0: 97.95%, 1: 2.05%",22.0,97.913209,...,0.039705,0.196261,0.000000,0.000000,0.000000,0.000000,0.000000,"0: 97.95%, 1: 2.05%",97.950,12
36,Tox21_AR_testing,292.0,22.35,23.32,1.0,1.0,2.0,"0: 98.97%, 1: 1.03%",15.0,98.973563,...,0.028618,0.232713,0.000000,0.000000,0.000000,0.000000,0.000000,"0: 98.97%, 1: 1.03%",98.970,3
37,Tox21_AR_training,9362.0,18.39,18.85,1.0,1.0,2.0,"0: 95.94%, 1: 4.06%",50.0,97.553997,...,0.031004,0.105638,0.061136,0.208270,0.430801,0.050519,0.175045,"0: 95.94%, 1: 4.06%",95.940,380
38,Tox21_ATAD5_evaluation,619.0,17.68,18.11,1.0,1.0,2.0,"0: 94.02%, 1: 5.98%",24.0,94.006081,...,0.022845,0.078891,0.033523,0.122755,0.037345,0.025685,0.091611,"0: 94.02%, 1: 5.98%",94.020,37
39,Tox21_ATAD5_testing,272.0,21.99,22.89,1.0,1.0,2.0,"0: 90.81%, 1: 9.19%",15.0,91.076720,...,0.038402,0.150197,0.057160,0.210932,0.089262,0.053925,0.185578,"0: 90.81%, 1: 9.19%",90.810,25
40,Tox21_ATAD5_training,9091.0,17.89,18.30,1.0,1.0,2.0,"0: 96.28%, 1: 3.72%",50.0,96.361236,...,0.007386,0.027972,0.014545,0.054972,0.043097,0.008126,0.031080,"0: 96.28%, 1: 3.72%",96.280,338
41,Tox21_AhR_evaluation,607.0,17.64,18.06,1.0,1.0,2.0,"0: 88.47%, 1: 11.53%",25.0,88.601366,...,0.014080,0.085866,0.025690,0.167444,0.138732,0.022666,0.135336,"0: 88.47%, 1: 11.53%",88.470,70
42,Tox21_AhR_testing,272.0,22.13,23.05,1.0,1.0,2.0,"0: 88.60%, 1: 11.40%",15.0,89.338624,...,0.059450,0.160010,0.087896,0.248292,0.111619,0.078950,0.224878,"0: 88.60%, 1: 11.40%",88.600,31
43,Tox21_AhR_training,8169.0,18.09,18.50,1.0,1.0,2.0,"0: 88.37%, 1: 11.63%",50.0,88.884766,...,0.006723,0.029384,0.013080,0.057513,0.037838,0.007629,0.032880,"0: 88.37%, 1: 11.63%",88.370,950
44,Tox21_ER-LBD_evaluation,599.0,17.75,18.17,1.0,1.0,2.0,"0: 96.66%, 1: 3.34%",24.0,96.812147,...,0.036876,0.151395,0.026395,0.203399,0.078667,0.043658,0.201469,"0: 96.66%, 1: 3.34%",96.660,20
45,Tox21_ER-LBD_testing,287.0,22.28,23.23,1.0,1.0,2.0,"0: 96.52%, 1: 3.48%",15.0,96.519704,...,0.039565,0.214644,0.000000,0.000000,0.000000,0.000000,0.000000,"0: 96.52%, 1: 3.48%",96.520,10
46,Tox21_ER-LBD_training,8753.0,18.06,18.47,1.0,1.0,2.0,"0: 94.90%, 1: 5.10%",49.0,96.002518,...,0.002984,0.038640,0.005924,0.075649,0.245805,0.005751,0.060365,"0: 94.90%, 1: 5.10%",94.900,446
47,Tox21_ER_evaluation,515.0,17.66,18.10,1.0,1.0,2.0,"0: 90.29%, 1: 9.71%",21.0,90.507542,...,0.024593,0.076597,0.040087,0.114957,0.036091,0.027908,0.080020,"0: 90.29%, 1: 9.71%",90.290,50
48,Tox21_ER_testing,265.0,22.16,23.13,1.0,1.0,2.0,"0: 89.81%, 1: 10.19%",15.0,89.625356,...,0.027832,0.083030,0.031064,0.119353,0.025833,0.032973,0.122918,"0: 89.81%, 1: 10.19%",89.810,27
49,Tox21_ER_training,7697.0,17.58,17.94,1.0,1.0,2.0,"0: 87.83%, 1: 12.17%",49.0,88.921573,...,0.003272,0.027720,0.006301,0.052362,0.161406,0.004968,0.037383,"0: 87.83%, 1: 12.17%",87.830,937
50,Tox21_HSE_evaluation,607.0,17.61,18.01,1.0,1.0,2.0,"0: 96.71%, 1: 3.29%",25.0,96.722951,...,0.035163,0.116281,0.042164,0.121439,0.018333,0.038849,0.115798,"0: 96.71%, 1: 3.29%",96.710,20
51,Tox21_HSE_testing,267.0,22.07,23.00,1.0,1.0,2.0,"0: 96.25%, 1: 3.75%",15.0,96.225071,...,0.045957,0.195699,0.021082,0.066667,0.005000,0.015811,0.050000,"0: 96.25%, 1: 3.75%",96.250,10
52,Tox21_HSE_training,8150.0,16.72,17.04,1.0,1.0,2.0,"0: 94.75%, 1: 5.25%",48.0,94.754601,...,0.002878,0.011294,0.005630,0.021795,0.004790,0.002996,0.011596,"0: 94.75%, 1: 5.25%",94.750,428
53,Tox21_MMP_evaluation,541.0,16.67,16.88,1.0,1.0,2.0,"0: 89.28%, 1: 10.72%",24.0,90.316498,...,0.017232,0.095917,0.033700,0.185058,0.236541,0.032517,0.169461,"0: 89.28%, 1: 10.72%",89.280,58
54,Tox21_MMP_testing,238.0,21.68,22.55,1.0,1.0,2.0,"0: 84.03%, 1: 15.97%",15.0,85.836957,...,0.033188,0.155025,0.063536,0.277114,0.298016,0.057239,0.278307,"0: 84.03%, 1: 15.97%",84.030,38
55,Tox21_MMP_training,7320.0,17.49,17.83,1.0,1.0,2.0,"0: 84.40%, 1: 15.60%",48.0,85.954918,...,0.008904,0.030344,0.016952,0.058387,0.197682,0.014141,0.048424,"0: 84.40%, 1: 15.60%",84.400,1142
56,Tox21_PPAR-gamma_evaluation,602.0,17.38,17.77,1.0,1.0,2.0,"0: 94.85%, 1: 5.15%",23.0,94.850546,...,0.033056,0.093732,0.019120,0.063715,0.006667,0.014055,0.046902,"0: 94.85%, 1: 5.15%",94.850,31
57,Tox21_PPAR-gamma_testing,267.0,22.04,22.93,1.0,1.0,2.0,"0: 94.38%, 1: 5.62%",15.0,94.447293,...,0.043091,0.193132,0.028216,0.139954,0.036667,0.031230,0.145219,"0: 94.38%, 1: 5.62%",94.380,15
58,Tox21_PPAR-gamma_training,8184.0,17.23,17.55,1.0,1.0,2.0,"0: 97.29%, 1: 2.71%",47.0,97.388816,...,0.008850,0.039555,0.017529,0.078244,0.045325,0.009670,0.046233,"0: 97.29%, 1: 2.71%",97.290,222
59,Tox21_aromatase_evaluation,528.0,16.74,16.99,1.0,1.0,2.0,"0: 92.61%, 1: 7.39%",22.0,92.720610,...,0.021284,0.094436,0.040515,0.183864,0.091952,0.028815,0.174645,"0: 92.61%, 1: 7.39%",92.610,39
60,Tox21_aromatase_testing,214.0,21.65,22.36,1.0,1.0,2.0,"0: 91.59%, 1: 8.41%",14.0,91.487013,...,0.023815,0.144579,0.038887,0.136222,0.023333,0.041722,0.144133,"0: 91.59%, 1: 8.41%",91.590,18
61,Tox21_aromatase_training,7226.0,17.50,17.79,1.0,1.0,2.0,"0: 95.02%, 1: 4.98%",47.0,95.060982,...,0.006168,0.027226,0.012108,0.053259,0.025354,0.006701,0.030332,"0: 95.02%, 1: 4.98%",95.020,360
62,Tox21_p53_evaluation,613.0,17.34,17.72,1.0,1.0,2.0,"0: 93.47%, 1: 6.53%",24.0,93.472501,...,0.022047,0.099734,0.046643,0.167787,0.049762,0.040477,0.146413,"0: 93.47%, 1: 6.53%",93.470,40
63,Tox21_p53_testing,269.0,22.14,23.04,1.0,1.0,2.0,"0: 89.59%, 1: 10.41%",15.0,89.705128,...,0.043396,0.129091,0.065580,0.184250,0.076262,0.072635,0.187598,"0: 89.59%, 1: 10.41%",89.590,28
64,Tox21_p53_training,8634.0,17.79,18.19,1.0,1.0,2.0,"0: 93.78%, 1: 6.22%",48.0,93.945991,...,0.006774,0.025493,0.013348,0.049933,0.046771,0.007522,0.028482,"0: 93.78%, 1: 6.22%",93.780,537
65,UACC257,39988.0,26.09,28.13,1.0,1.0,2.0,"0: 95.89%, 1: 4.11%",64.0,96.082570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0: 95.89%, 1: 4.11%",95.890,1644

## Load and clean data

first we find the columns where path boost perform the best

In [8]:
# get columns that refers to accuracy
columns = df.columns
acc_columns = [col for col in columns if ("acc" in col.lower()) and "std" not in col.lower()]
acc_columns
# get the datasets where path boost perform the best (columns "PathBoostAccuracy_times 100")

ac_df = df[acc_columns]  # acccuracy dataset

best_performances_dataset = ac_df.loc[ac_df["PathBoostAccuracy_times 100"] >= ac_df.max(axis=1)]

best_performances_dataset = df.loc[best_performances_dataset.index]
best_performances_dataset[["Dataset", "n_graphs_firs_class"]]

                        Dataset  n_graphs_firs_class
0                          AIDS                  400
8                         MCF-7                 2294
11                        MUTAG                  125
12                      NCI-H23                 2058
17                PROTEINS_full                  451
23                       SF-295                 2026
25                       SW-620                 2412
27                    SYNTHETIC                  150
32         Tox21_ARE_evaluation                   91
34           Tox21_ARE_training                 1098
36             Tox21_AR_testing                    3
38       Tox21_ATAD5_evaluation                   37
39          Tox21_ATAD5_testing                   25
41         Tox21_AhR_evaluation                   70
42            Tox21_AhR_testing                   31
44      Tox21_ER-LBD_evaluation                   20
45         Tox21_ER-LBD_testing                   10
47          Tox21_ER_evaluation                   50
48             Tox21_ER_testing                   27
49            Tox21_ER_training                  937
50         Tox21_HSE_evaluation                   20
51            Tox21_HSE_testing                   10
53         Tox21_MMP_evaluation                   58
56  Tox21_PPAR-gamma_evaluation                   31
57     Tox21_PPAR-gamma_testing                   15
59   Tox21_aromatase_evaluation                   39
60      Tox21_aromatase_testing                   18
62         Tox21_p53_evaluation                   40
63            Tox21_p53_testing                   28
64           Tox21_p53_training                  537
65                      UACC257                 1644

In [9]:
#select only the ones where the percentage is bigger than 15
#df['fist_class_percentage']
percent = 85




print(len(df.loc[df['fist_class_percentage'] < percent, ['Dataset'] + acc_columns]))
print(len(best_performances_dataset.loc[df['fist_class_percentage'] < percent]))
df.loc[df['fist_class_percentage'] < percent, ['Dataset'] + acc_columns]

12
6

,Dataset,PathBoostAccuracy_times 100,PathBoostAccuracy,GNNAccuracy,KernelAccuracy,PathBoostAccuracy_times_100,Weisfeiler-Lehman subtree kernel_accuracy,Weisfeiler-Lehman subtree kernel linear_accuracy,Graphlet kernel_accuracy,Graphlet kernel linear_accuracy,Shortest-path kernel_accuracy,Shortest-path kernel linear_accuracy,Weisfeiler-Lehman optimal assignment kernel_accuracy,GNN_accuracy,GNN_balanced_accuracy,PB_accuracy,PB_balanced_accuracy
0,AIDS,99.330000,0.993300,NaN,None,99.330000,96.425000,96.595000,99.035000,99.035000,99.015000,99.075000,None,NaN,NaN,99.170000,NaN
1,BZR,86.764634,0.867646,82.511585,None,86.764634,86.901829,86.920732,82.297561,81.995122,82.297561,81.995122,None,0.821482,0.688181,84.564024,0.685640
5,DHFR,78.190000,0.781900,80.031579,None,78.190000,81.451930,81.308772,74.520526,72.898947,74.432281,72.898947,None,NaN,NaN,NaN,NaN
11,MUTAG,89.111111,0.891111,82.827485,None,89.111111,76.350877,76.327485,85.324561,83.350877,85.324561,83.438596,None,0.832953,0.824600,86.324561,0.839085
17,PROTEINS_full,78.995656,0.789957,71.496863,None,78.995656,73.055502,73.033542,NaN,72.578266,NaN,72.109073,None,0.756348,NaN,71.487049,0.691782
18,PTC_FM,61.800840,0.618008,59.545378,None,61.800840,62.842017,62.583193,56.637815,57.826891,56.637815,58.221849,None,0.593496,0.557007,57.093277,0.534749
27,SYNTHETIC,62.266667,0.622667,48.533333,None,62.266667,45.533333,45.333333,45.733333,45.733333,45.733333,45.733333,None,NaN,NaN,NaN,NaN
32,Tox21_ARE_evaluation,83.370455,0.833705,81.954545,None,83.370455,81.268182,82.261364,82.242208,82.787013,82.535714,82.784091,None,0.813172,0.538534,80.162013,0.520917
33,Tox21_ARE_testing,79.398551,0.793986,79.206522,None,79.398551,78.059783,78.409420,80.632246,78.465580,80.204710,79.000000,None,0.789674,0.599662,76.329710,0.557759
34,Tox21_ARE_training,84.785949,0.847859,NaN,None,84.785949,NaN,NaN,NaN,84.743975,NaN,84.743975,None,NaN,NaN,84.719028,0.519862
54,Tox21_MMP_testing,85.836957,0.858370,82.007246,None,85.836957,86.313406,86.226449,82.465580,82.735507,82.340580,82.987319,None,0.829638,0.630598,83.643116,0.636798
55,Tox21_MMP_training,85.954918,0.859549,NaN,None,85.954918,91.143443,NaN,NaN,84.956284,NaN,84.991803,None,NaN,NaN,85.586066,0.587563

## Filter by class balance threshold

In [10]:

columns_extended = [
    "Dataset",
    "Graphs",
    "AvgNodes",
    "AvgEdges",
    "NodeFeatures",
    "EdgeFeatures",
    "TotalFeatures",
    "ClassPercentages",
    "CatAttrClasses",
    "PathBoostAccuracy_times 100",
    "PathBoostAccuracy",
    "PathBoostStd10",
    "PathBoostStd100",
    "GNNAccuracy",
    "GNNStd10",
    "GNNStd100",
    "KernelAccuracy",
    "source_file",
    "source_file_dup",
    "PathBoostAccuracy_times_100",
    "Weisfeiler-Lehman subtree kernel_accuracy",
    "Weisfeiler-Lehman subtree kernel_std_10",
    "Weisfeiler-Lehman subtree kernel_std_100",
    "Weisfeiler-Lehman subtree kernel linear_accuracy",
    "Weisfeiler-Lehman subtree kernel linear_std_10",
    "Weisfeiler-Lehman subtree kernel linear_std_100",
    "Graphlet kernel_accuracy",
    "Graphlet kernel_std_10",
    "Graphlet kernel_std_100",
    "Graphlet kernel linear_accuracy",
    "Graphlet kernel linear_std_10",
    "Graphlet kernel linear_std_100",
    "Shortest-path kernel_accuracy",
    "Shortest-path kernel_std_10",
    "Shortest-path kernel_std_100",
    "Shortest-path kernel linear_accuracy",
    "Shortest-path kernel linear_std_10",
    "Shortest-path kernel linear_std_100",
    "Weisfeiler-Lehman optimal assignment kernel_accuracy",
    "Weisfeiler-Lehman optimal assignment kernel_std_10",
    "Weisfeiler-Lehman optimal assignment kernel_std_100",
    "GNN_accuracy",
    "GNN_accuracy_std10",
    "GNN_accuracy_std100",
    "GNN_balanced_accuracy",
    "GNN_balanced_accuracy_std10",
    "GNN_balanced_accuracy_std100",
    "GNN_f1",
    "GNN_f1_macro",
    "GNN_f1_macro_std10",
    "GNN_f1_macro_std100",
    "GNN_f1_std10",
    "GNN_f1_std100",
    "GNN_recall",
    "GNN_recall_std10",
    "GNN_recall_std100",
    "GNN_roc_auc",
       "GNN_roc_auc_std10",
    "GNN_roc_auc_std100",
    "PB_accuracy",
    "PB_accuracy_std10",
    "PB_accuracy_std100",
    "PB_balanced_accuracy",
    "PB_balanced_accuracy_std10",
    "PB_balanced_accuracy_std100",
    "PB_f1",
    "PB_f1_macro",
    "PB_f1_macro_std10",
    "PB_f1_macro_std100",
    "PB_f1_std10",
    "PB_f1_std100",
    "PB_recall",
    "PB_recall_std10",
    "PB_recall_std100"
]



columns_extended = [
    "Dataset",
    "PathBoostAccuracy_times 100",
    "PathBoostStd10",
    "GNNAccuracy",
    "GNNStd10",
    "Weisfeiler-Lehman subtree kernel_accuracy",
    "Weisfeiler-Lehman subtree kernel_std_10",
    "Weisfeiler-Lehman subtree kernel linear_accuracy",
    "Weisfeiler-Lehman subtree kernel linear_std_10",
    "Graphlet kernel_accuracy",
    "Graphlet kernel_std_10",
    "Graphlet kernel linear_accuracy",
    "Graphlet kernel linear_std_10",
    "Shortest-path kernel_accuracy",
    "Shortest-path kernel_std_10",
    "Shortest-path kernel linear_accuracy",
    "Shortest-path kernel linear_std_10",
    "GNN_f1",
    "GNN_f1_std10",
    "GNN_f1_macro",
    "GNN_f1_macro_std10",
    "PB_f1_macro",
    "PB_f1_macro_std10",
    "PB_f1",
    "PB_f1_std10",

]


columns_to_multiply = [
    "PathBoostStd10",
    "GNN_f1",
    "GNN_f1_std10",
    "GNN_f1_macro",
    "GNN_f1_macro_std10",
    "PB_f1_macro",
    "PB_f1_macro_std10",
    "PB_f1",
    "PB_f1_std10"
]

pairwise_col = [
("PathBoostAccuracy_times 100",
    "PathBoostStd10"),
("GNNAccuracy",
    "GNNStd10"),
("Weisfeiler-Lehman subtree kernel_accuracy",
    "Weisfeiler-Lehman subtree kernel_std_10"),
("Weisfeiler-Lehman subtree kernel linear_accuracy",
    "Weisfeiler-Lehman subtree kernel linear_std_10"),
("Graphlet kernel_accuracy",
    "Graphlet kernel_std_10"),
("Graphlet kernel linear_accuracy",
    "Graphlet kernel linear_std_10"),
("Shortest-path kernel_accuracy",
    "Shortest-path kernel_std_10"),
("Shortest-path kernel linear_accuracy",
    "Shortest-path kernel linear_std_10"),
("GNN_f1",
    "GNN_f1_std10"),
("GNN_f1_macro",
    "GNN_f1_macro_std10"),
("PB_f1_macro",
    "PB_f1_macro_std10"),
("PB_f1",
    "PB_f1_std10"),
]

## Define columns for export

## Format and export results to CSV

In [11]:
print(len(df.loc[df['fist_class_percentage'] < percent, ['Dataset'] + acc_columns]))
print(len(best_performances_dataset.loc[df['fist_class_percentage'] < percent]))

latex_table= df.loc[df['fist_class_percentage'] < percent, columns_extended]

latex_table[columns_to_multiply]=latex_table[columns_to_multiply]*100


latex_table= latex_table.round(2).fillna('')


for col_acc, col_std in pairwise_col:
    latex_table[col_acc] = latex_table[col_acc].astype(str) + " ± " + latex_table[col_std].astype(str)
    latex_table = latex_table.drop(columns=[col_std])

#remove the +- ymbol in the empty cells
def remove_plus_minus(x):
    try:
        if '±' in x:
            if x.strip() == '±':
                return ''
            else:
                return x
        else:
            return x
    except:
        return x
latex_table = latex_table.map(remove_plus_minus)





latex_table.to_csv("pathboost_best_performing_datasets_under_85_percent.csv", index=False)

12
6

In [12]:
# check correlation

numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns


df[numeric_columns].corr()['PathBoostAccuracy_times 100']

Graphs                   0.245526
AvgNodes                -0.271010
AvgEdges                -0.335986
NodeFeatures            -0.144701
EdgeFeatures             0.343303
                           ...
PB_recall               -0.245115
PB_recall_std10         -0.409773
PB_recall_std100        -0.463409
fist_class_percentage    0.549714
n_graphs_firs_class      0.081170
Name: PathBoostAccuracy_times 100, Length: 68, dtype: float64

## Correlation analysis